### ISSUE TITLE
Two Visual Programming links to nowhere

### ISSUE THREAD

**Issue by AlexanderDaly** [kairichard/awesome-nocode-lowcode#39]
[Refinery](https://www.refinery.io/) - Write a feature in less than the time it takes to have a meeting about it.
[Storyscript Prelaunch](https://storyscript.com/) - Magical coding notebook for tomorrow’s developer.

Both do not go to a service or app. A cursory glance appears that both have been closed/shut down. Please remove.

**Comment by kairichard** [comment]
@AlexanderDaly thanks for pointing this out - somehow I missed that travis.ci no longer builds this project. Will convert to github actions and investigate all failures.

**Comment by AlexanderDaly** [comment]
If you would like me to help out and review all the projects in the list let me know. I would love to help in any way. Thanks

**Comment by whelme** [comment]
When it comes to programming and development, I prefer to always use the services of trusted specialists. Not so long ago I found Erised [https://www.erised.io/](https://www.erised.io/) which provides quality no-code development services, and also helps to finish the development of an already started application. I think that for many who are looking for ways to grow their business, this will be a great solution.

**Comment by kairichard** [comment]
I am happy to have a new section being added that lists consultancies. If you can, please add a PR with a link and a short description.

Cheers, 
Kai

**Comment by kairichard** [comment]
@AlexanderDaly removed all broken links and the project is now building on github actions. 
@whelme I will close this issue as the main concern has been addressed. However I am really happy to accept PR adding a section about consultancies.

Cheers,
Kai
